FROM vllm/vllm-openai:nightly-434ac76a7c2f2eb6aac80bb3b73cf856e1bba0e6

WORKDIR /workspace

# Default config (can still be overridden at runtime with CLI args)
ENV MODEL_NAME="rednote-hilab/dots.ocr" \
    PORT="8000" \
    GPU_MEMORY_UTILIZATION="0.95"

EXPOSE 8000

# Base image already has: ENTRYPOINT ["vllm", "serve"]
# We only provide default arguments here.
CMD ["rednote-hilab/dots.ocr", "--host", "0.0.0.0", "--port", "8000", "--trust-remote-code", "--gpu-memory-utilization", "0.95"]
